version: '3.8'
services:
  api:
    image: lucasteles/lobby-server
    build:
      dockerfile: Dockerfile
    environment:
      UdpHost: ''
    networks:
        - local-network
    ports:
      - '9999:8080/tcp'
      - '8888:8888/udp'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M

networks:
    local-network:
        driver: bridge
